import{a as d,S as L,i as y}from"./assets/vendor-6e0bf343.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();d.defaults.baseURL="https://pixabay.com/api/";async function p(r,t=1){const i="43383270-573d9e698d4e4b734db4ac29f",s=new URLSearchParams({key:i,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});try{return(await d.get("",{params:s})).data}catch(e){console.log(e)}}const f=document.querySelector(".gallery");function m(r){const t=r.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:n,comments:g,downloads:b})=>`<li class="gallery-item">
          <a href="${s}">
          <img src="${i}" alt="${e}" />
          </a>
          <ul>
            <li><b>Likes</b> ${o}</li>
            <li><b>Views</b> ${n}</li>
            <li><b>Comments</b> ${g}</li>
            <li><b>Downloads</b> ${b}</li>
          </ul>
        </li>`).join("");f.insertAdjacentHTML("beforeend",t)}function S(){f.innerHTML=""}const v=document.querySelector(".search-form"),u=document.querySelector("#search-input"),l=document.querySelector(".loader"),c=document.querySelector(".load-more-btn"),h=new L(".gallery a",{captionsData:"alt",captionDelay:250});l.style.display="none";c.style.display="none";v.addEventListener("submit",w);c.addEventListener("click",q);let a=1;async function w(r){if(r.preventDefault(),u.value.trim()!==""){l.style.display="block",S(),a=1;try{const t=await p(u.value.trim(),a);t.hits.length===0&&y.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),m(t.hits),t.totalHits>15?c.style.display="block":c.style.display="none",h.refresh()}catch(t){console.log(t)}finally{l.style.display="none"}}}async function q(){a+=1;try{l.style.display="block";const r=await p(u.value.trim(),a);m(r.hits),h.refresh();const t=document.querySelector(".gallery-item");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}Math.ceil(r.totalHits/15)===a&&(c.style.display="none",y.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"}))}catch(r){console.log(r)}finally{l.style.display="none"}}
//# sourceMappingURL=commonHelpers.js.map
