import{a as d,S as L,i as y}from"./assets/vendor-6e0bf343.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();d.defaults.baseURL="https://pixabay.com/api/";async function p(s,t=1){const r="43383270-573d9e698d4e4b734db4ac29f",n=new URLSearchParams({key:r,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});try{return(await d.get("",{params:n})).data}catch(e){console.log(e)}}const f=document.querySelector(".gallery");function m(s){const t=s.map(({webformatURL:r,largeImageURL:n,tags:e,likes:o,views:i,comments:g,downloads:b})=>`<li class="gallery-item">
          <a href="${n}">
          <img src="${r}" alt="${e}" />
          </a>
          <ul>
            <li><b>Likes</b> ${o}</li>
            <li><b>Views</b> ${i}</li>
            <li><b>Comments</b> ${g}</li>
            <li><b>Downloads</b> ${b}</li>
          </ul>
        </li>`).join("");f.insertAdjacentHTML("beforeend",t)}function S(){f.innerHTML=""}const v=document.querySelector(".search-form"),u=document.querySelector("#search-input"),l=document.querySelector(".loader"),c=document.querySelector(".load-more-btn"),h=new L(".gallery a",{captionsData:"alt",captionDelay:250});l.style.display="none";c.style.display="none";v.addEventListener("submit",w);c.addEventListener("click",q);let a=1;async function w(s){if(s.preventDefault(),u.value.trim()!==""){l.style.display="block",S(),a=1;try{const t=await p(u.value.trim(),a);t.hits.length===0&&y.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),m(t.hits),t.totalHits>15?c.style.display="block":c.style.display="none",h.refresh()}catch(t){console.log(t)}finally{l.style.display="none"}}}async function q(s){a+=1;try{l.style.display="block";const t=await p(u.value.trim(),a);m(t.hits),h.refresh();const r=document.querySelector(".gallery-item");if(r){const e=r.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}Math.ceil(t.totalHits/15)===a&&(c.style.display="none",y.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"}))}catch(t){console.log(t)}finally{l.style.display="none"}}
//# sourceMappingURL=commonHelpers.js.map
